"""Please work

Revision ID: c75cd1e6ef46
Revises: ff6386765262
Create Date: 2023-09-15 13:50:07.336708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75cd1e6ef46'
down_revision = 'ff6386765262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('first_name', sa.String(length=50), nullable=False, server_default=""))
    op.add_column('user_table', sa.Column('last_name', sa.String(length=50), nullable=False, server_default=""))
    op.add_column('user_table', sa.Column('tdee', sa.Integer(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user_table', 'tdee')
    op.drop_column('user_table', 'last_name')
    op.drop_column('user_table', 'first_name')
    # ### end Alembic commands ###
