"""empty message

Revision ID: ff6386765262
Revises: eeeb70e65e2a
Create Date: 2023-09-15 09:50:48.955607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6386765262'
down_revision = 'eeeb70e65e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_day_log_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_daily_calories_eaten', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_and_log_association_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_day_log_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_day_log_id'], ['current_day_log_table.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('item_table', 'calories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_table', sa.Column('calories', sa.INTEGER(), nullable=False))
    op.drop_table('item_and_log_association_table')
    op.drop_table('current_day_log_table')
    # ### end Alembic commands ###
